---
name: cleaner

on:
  pull_request:
    types:
    - closed

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: refs/heads/${{ github.base_ref }}
    - run: |
        env | sort
        echo "github.base_ref: ${{ github.base_ref }}"
        echo "github.base_sha: ${{ github.base_sha }}"
        echo "github.event.action: ${{ github.event.action }}"
        echo "github.event.pull_request.merged: ${{ github.event.pull_request.merged }}"
        git log -n 5
