---
name: runner

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  select:
    runs-on: ubuntu-latest
    outputs:
      projects: ${{ steps.filter.outputs.changes }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: .github/projects.yml
  hook:
    if: ${{ needs.select.outputs.projects != [] }}
    needs: select
    strategy:
      matrix:
        project: ${{ fromJSON(needs.select.outputs.projects) }}
    runs-on: ubuntu-latest
    steps:
    - run: echo "${{ matrix.project }}"
