---
name: runner

on:
  push:
    branches:
    - master
    tags:
    - v*
  pull_request:
    branches:
    - master
    types:
    - opened
    - synchronize
    - reopened
  workflow_dispatch:
    inputs:
      deploy_group:
        description: Group name in inventory file
        default: dev1
      deploy_state:
        description: "One of the states: staging, current, restore, absent, balancer, sync, backup, recovery, test"
        default: staging

jobs:
  select:
    runs-on: ubuntu-latest
    outputs:
      projects: ${{ steps.filter.outputs.changes }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: .github/projects.yml
    - run: |
        env | sort
        echo "github.workflow: ${{ github.workflow }}"
        echo "github.job: ${{ github.job }}"
        echo "github.base_ref: ${{ github.base_ref }}"
        echo "github.base_sha: ${{ github.base_sha }}"
        echo "github.event.action: ${{ github.event.action }}"
        echo "github.event.pull_request: ${{ toJSON(github.event.pull_request) }}"
        echo "github.event.repository: ${{ toJSON(github.event.repository) }}"
        git log -n 5
  run:
    if: ${{ needs.select.outputs.projects != '[]' }}
    needs: select
    strategy:
      matrix:
        project: ${{ fromJSON(needs.select.outputs.projects) }}
    runs-on: ubuntu-latest
    steps:
    - run: |
        env | sort
        echo "matrix.project: ${{ matrix.project }}"
        echo "github.workflow: ${{ github.workflow }}"
        echo "github.job: ${{ github.job }}"
        echo "github.base_ref: ${{ github.base_ref }}"
        echo "github.event.action: ${{ github.event.action }}"
        echo "github.event.pull_request.merged: ${{ github.event.pull_request.merged }}"
